#include "native_format.h"

#include <chrono>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <numeric>
#include <openssl/sha.h>
#include <sstream>
#include <sys/resource.h>
#include <unordered_set>
#include <vector>

namespace {
using namespace z0b;
constexpr uint8_t E=0,O=1,C=2,F=3;
struct RefSlot { uint32_t id,version; uint16_t role; bool valid; };
struct RefZone { uint8_t state=E; uint32_t live=0; std::vector<RefSlot> log; };
struct RefPage { Key key{}; uint32_t version=0,zone=0,slot=0,page_bytes=4096;uint16_t role=0;bool live=false; };
struct Mark { uint64_t ordinal=0,seq=0;int64_t sub=-1; };
struct RefCycle { Mark begin{},last{},trigger{};uint64_t appends=0,app_bytes=0,moved=0;uint32_t cap=0,victim=0,dest=0,free_before=0,free_after=0;std::map<uint16_t,uint64_t>roles;std::vector<uint64_t>updates,batches; };
struct Acc { bool active=false;Mark begin{},last{};uint64_t appends=0,app_bytes=0;std::unordered_set<uint64_t>updates,batches; };
struct RefAudit {uint64_t ordinal=0,seq=0;int64_t page=-1;uint8_t op=0;uint32_t destination=UINT32_MAX;uint8_t gc=0;uint32_t victim=UINT32_MAX,moved=0;uint64_t argument=0,update=0,batch=0;DeltaAccumulator deltas;RefAudit(uint64_t ordinal_value,uint64_t seq_value,int64_t page_value,uint8_t op_value):ordinal(ordinal_value),seq(seq_value),page(page_value),op(op_value){}};

class Reference {
 public:
  Reference(std::span<const InitialRecord> initial,std::span<const NormalRecord> normal,
            std::span<const LifecycleRecord> life,uint32_t cap,uint32_t spares,
            std::string placement,uint64_t seed,std::string cleaner)
      :initial_(initial),normal_(normal),life_(life),cap_(cap),h_(spares),placement_(std::move(placement)),seed_(seed),cleaner_(std::move(cleaner)){
    if(!cap_||h_<2||(cleaner_!="greedy"&&cleaner_!="oracle"))throw Error("bad reference configuration");
    catalogue();place();SHA256_Init(&transition_ctx_);static constexpr char domain[]="Z0BTRANSITION1";SHA256_Update(&transition_ctx_,domain,sizeof(domain)-1);verify(true);
  }
  void run(){size_t n=0,l=0;while(n<normal_.size()||l<life_.size()){bool take=l<life_.size()&&(n==normal_.size()||life_[l].global_seq<normal_[n].global_seq);if(l<life_.size()&&n<normal_.size()&&life_[l].global_seq==normal_[n].global_seq)throw Error("sequence collision");++ordinal_;if(take)truncate(life_[l++]);else write(normal_[n++]);}verify(false);}
  void output(std::ostream&o)const{o<<"{\n  \"schema\":\"zns-ann-z0b-native-reference-v1\",\n  \"engine\":\"reference\",\n  \"status\":\"pass\",\n  \"sequence_only\":true,\n  \"temporal_fields_used\":false,\n  \"placement\":\""<<json_escape(placement_)<<"\",\n  \"random_seed\":"<<seed_<<",\n  \"cleaner\":\""<<cleaner_<<"\",\n  \"initial_image\":{\"logical_bytes\":"<<initial_logical_bytes_<<",\"allocated_bytes\":"<<initial_blocks_*4096ULL<<",\"page_count\":"<<initial_blocks_<<"},\n  \"bytes\":{\"application_returned_bytes\":"<<app_<<",\"normalized_fragment_bytes\":"<<fragment_<<",\"allocated_append_bytes\":"<<user_*4096ULL<<",\"replacement_rmw_read_bytes\":"<<rmw_<<",\"new_page_zero_fill_bytes\":"<<zero_<<",\"relocation_allocated_bytes\":"<<copied_*4096ULL<<"},\n  \"host_wa_fraction\":\""<<user_+copied_<<'/'<<user_<<"\",\n  \"reset_count\":"<<resets_<<",\n  \"complete_cycle_count\":"<<cycles_.size()<<",\n  \"tail\":{\"complete_cycle\":false,\"allocated_new_blocks\":"<<acc_.appends<<",\"allocated_append_bytes\":"<<acc_.appends*4096ULL<<",\"application_returned_bytes\":"<<acc_.app_bytes<<"},\n  \"victim_sequence\":[";for(size_t i=0;i<victims_.size();++i){if(i)o<<',';o<<victims_[i];}o<<"],\n  \"cycles\":[";for(size_t i=0;i<cycles_.size();++i){if(i)o<<',';cycle_json(o,cycles_[i],i+1);}o<<"],\n  \"final_state_sha256\":\""<<digest()<<"\",\n  \"transition_rolling_sha256\":\""<<transition_digest()<<"\",\n  \"comparable_result\":";comparable(o);o<<"\n}\n";}
  size_t page_count()const{return pages_.size();}
 private:
  std::span<const InitialRecord> initial_;std::span<const NormalRecord> normal_;std::span<const LifecycleRecord> life_;
  uint32_t cap_,h_;std::string placement_;uint64_t seed_;std::string cleaner_;
  std::vector<RefPage>pages_;std::unordered_map<Key,uint32_t,KeyHash>index_;std::unordered_map<uint64_t,std::vector<uint32_t>>by_object_;
  std::vector<RefZone>zones_;std::vector<uint8_t>free_;int64_t head_=-1;uint64_t ordinal_=0;Mark prior_{};bool prior_valid_=false;
  uint64_t initial_blocks_=0,initial_logical_bytes_=0,user_=0,copied_=0,erased_=0,resets_=0,app_=0,fragment_=0,rmw_=0,zero_=0;
  Acc acc_;std::vector<RefCycle>cycles_;std::vector<uint32_t>victims_;
  SHA256_CTX transition_ctx_{};
  std::vector<unsigned char> audit_chunk_;

  void catalogue(){index_.reserve(initial_.size()*1.35+1024);const InitialRecord*last=nullptr;for(const auto&r:initial_){if(!r.page_bytes||r.page_bytes>4096||r.aligned_offset%4096||r.reserved)throw Error("bad initial");if(last&&!key_less(*last,r))throw Error("initial order");last=&r;Key k{r.object_incarnation,r.aligned_offset};uint32_t id=pages_.size();if(!index_.emplace(k,id).second)throw Error("duplicate initial");pages_.push_back(RefPage{k,0,0,0,r.page_bytes,r.role,true});initial_logical_bytes_+=r.page_bytes;by_object_[k.object].push_back(id);}initial_blocks_=pages_.size();}
  std::array<unsigned char,32> rank(uint32_t id)const{const auto&p=pages_[id];std::string s="z0b-random-packing-v1";s.push_back(0);s+=std::to_string(seed_);s.push_back(0);s+=std::to_string(p.key.object)+":"+std::to_string(p.key.offset);std::array<unsigned char,32>d{};SHA256(reinterpret_cast<const unsigned char*>(s.data()),s.size(),d.data());return d;}
  void place(){std::vector<uint32_t>order(pages_.size());std::iota(order.begin(),order.end(),0);if(placement_=="random"){std::vector<std::pair<std::array<unsigned char,32>,uint32_t>>v;v.reserve(order.size());for(auto id:order)v.push_back({rank(id),id});std::sort(v.begin(),v.end(),[&](const auto&a,const auto&b){if(a.first!=b.first)return a.first<b.first;const auto&x=pages_[a.second],&y=pages_[b.second];return std::tie(x.role,x.key.object,x.key.offset)<std::tie(y.role,y.key.object,y.key.offset);});for(size_t i=0;i<v.size();++i)order[i]=v[i].second;}else if(placement_=="oracle"){std::vector<uint32_t>hits(pages_.size());for(const auto&e:normal_){auto it=index_.find(Key{e.object_incarnation,e.aligned_offset});if(it!=index_.end()&&hits[it->second]!=UINT32_MAX)++hits[it->second];}std::sort(order.begin(),order.end(),[&](auto a,auto b){if(hits[a]!=hits[b])return hits[a]>hits[b];const auto&x=pages_[a],&y=pages_[b];return std::tie(x.role,x.key.object,x.key.offset)<std::tie(y.role,y.key.object,y.key.offset);});}else if(placement_!="canonical"&&placement_!="role")throw Error("bad placement");bool have=false;uint16_t previous_role=0;for(auto id:order){uint16_t role=pages_[id].role;if(zones_.empty()||zones_.back().log.size()==cap_||(placement_=="role"&&have&&role!=previous_role&&!zones_.back().log.empty())){if(!zones_.empty())zones_.back().state=zones_.back().log.size()==cap_?F:C;zones_.push_back(RefZone{});zones_.back().log.reserve(std::min<uint64_t>(cap_,pages_.size()));}auto&z=zones_.back();uint32_t zid=zones_.size()-1,sid=z.log.size();z.log.push_back({id,0,role,true});++z.live;pages_[id].zone=zid;pages_[id].slot=sid;previous_role=role;have=true;}if(zones_.empty())throw Error("empty initial");zones_.back().state=zones_.back().log.size()==cap_?F:C;if(zones_.back().state==C)head_=zones_.size()-1;size_t ordinary=zones_.size();zones_.resize(ordinary+h_);free_.assign(zones_.size(),0);for(size_t z=ordinary;z<zones_.size();++z)free_[z]=1;}
  uint32_t free_count()const{return std::accumulate(free_.begin(),free_.end(),0U);}
  uint32_t first_free()const{for(uint32_t z=0;z<free_.size();++z)if(free_[z])return z;throw Error("no free zone");}
  void order(uint64_t seq,int64_t sub){if(!seq||(prior_valid_&&std::tie(seq,sub)<=std::tie(prior_.seq,prior_.sub)))throw Error("bad order");prior_={ordinal_,seq,sub};prior_valid_=true;}
  Mark mark(uint64_t seq,int64_t sub)const{return {ordinal_,seq,sub};}
  uint64_t occupied()const{return initial_blocks_+user_+copied_-erased_;}
  uint64_t live_total()const{uint64_t n=0;for(const auto&z:zones_)n+=z.live;return n;}
  void open(uint32_t z){if(zones_[z].state!=E&&zones_[z].state!=C)throw Error("reference open");if(zones_[z].state==E)free_[z]=0;zones_[z].state=O;head_=z;}
  void full(uint32_t z){if(zones_[z].log.size()==cap_){zones_[z].state=F;if(head_==z)head_=-1;}}
  uint32_t choose(uint32_t destination)const{uint32_t best=UINT32_MAX,bestlive=UINT32_MAX;for(uint32_t z=0;z<zones_.size();++z)if(z!=destination&&static_cast<int64_t>(z)!=head_&&zones_[z].state==F){if(zones_[z].live<bestlive||(zones_[z].live==bestlive&&z<best)){best=z;bestlive=zones_[z].live;}}if(best==UINT32_MAX)throw Error("no victim");return best;}
  static std::vector<uint64_t> sorted(const std::unordered_set<uint64_t>&s){std::vector<uint64_t>v(s.begin(),s.end());std::sort(v.begin(),v.end());return v;}
  void collect(const Mark&trigger,RefAudit&a){if(free_count()!=1)throw Error("reference GC reserve");uint32_t dest=first_free(),victim=choose(dest),moved=zones_[victim].live;if(moved>=cap_)throw Error("reference no reclaim");a.gc=1;a.victim=victim;a.moved=moved;a.destination=dest;std::map<uint16_t,uint64_t>roles;for(auto&s:zones_[victim].log)if(s.valid)++roles[s.role];uint32_t before=free_count();open(dest);auto&source=zones_[victim];auto&target=zones_[dest];for(uint32_t sid=0;sid<source.log.size();++sid){auto&s=source.log[sid];if(!s.valid)continue;auto&p=pages_[s.id];if(!p.live||p.zone!=victim||p.slot!=sid)throw Error("reference stale GC map");uint32_t ds=target.log.size();a.deltas.add({p.key.object,p.key.offset,p.version,victim,sid,p.version,dest,ds,p.role,1,1,1});target.log.push_back({s.id,s.version,s.role,true});++target.live;s.valid=false;--source.live;p.zone=dest;p.slot=ds;++copied_;}if(source.live)throw Error("reference reset live");erased_+=source.log.size();source.log.clear();source.state=E;free_[victim]=1;++resets_;victims_.push_back(victim);full(dest);if(head_<0)throw Error("reference relocation overflow");if(!acc_.active||!acc_.appends)throw Error("empty reference cycle");RefCycle c;c.begin=acc_.begin;c.last=acc_.last;c.trigger=trigger;c.appends=acc_.appends;c.app_bytes=acc_.app_bytes;c.moved=moved;c.cap=cap_;c.victim=victim;c.dest=dest;c.free_before=before;c.free_after=free_count();c.roles=std::move(roles);c.updates=sorted(acc_.updates);c.batches=sorted(acc_.batches);cycles_.push_back(std::move(c));acc_=Acc{};}
  uint32_t room(const Mark&trigger,RefAudit&a){if(head_>=0){auto&z=zones_[head_];if(z.state==C)open(head_);if(z.state==O&&z.log.size()<cap_){a.destination=head_;return head_;}}if(free_count()>=2){uint32_t z=first_free();open(z);a.destination=z;return z;}if(free_count()==1){collect(trigger,a);return head_;}throw Error("reference free exhausted");}
  void note(const Mark&m,uint64_t update,uint64_t batch,bool append){if(append&&!acc_.active){acc_.active=true;acc_.begin=m;}if(acc_.active){acc_.last=m;if(update)acc_.updates.insert(update);if(batch)acc_.batches.insert(batch);}}
  void write(const NormalRecord&e){order(e.global_seq,e.page_index_within_request);if(!e.fragment_bytes||e.fragment_bytes>4096||e.aligned_offset%4096||e.reserved)throw Error("bad normalized");Mark m=mark(e.global_seq,e.page_index_within_request);RefAudit a{ordinal_,e.global_seq,static_cast<int64_t>(e.page_index_within_request),1};a.argument=e.fragment_bytes;a.update=e.update_id;a.batch=e.batch_id;uint32_t dest=room(m,a);Key k{e.object_incarnation,e.aligned_offset};auto it=index_.find(k);uint32_t id;bool replace=it!=index_.end()&&pages_[it->second].live;if(it==index_.end()){id=pages_.size();index_[k]=id;pages_.push_back(RefPage{k,0,0,0,4096,e.role,false});by_object_[k.object].push_back(id);}else id=it->second;auto&p=pages_[id];uint32_t oldver=p.version,oldzone=p.zone,oldslot=p.slot;uint8_t oldlive=p.live;if(replace&&p.role!=e.role)throw Error("reference role change");uint32_t ver=replace?p.version+1:1;auto&zone=zones_[dest];uint32_t slot=zone.log.size();zone.log.push_back({id,ver,e.role,true});++zone.live;if(replace){auto&old=zones_[p.zone].log[p.slot];if(!old.valid||old.version!=p.version)throw Error("reference stale overwrite");old.valid=false;--zones_[p.zone].live;rmw_+=4096-e.fragment_bytes;}else zero_+=4096-e.fragment_bytes;p.version=ver;p.zone=dest;p.slot=slot;p.role=e.role;p.live=true;a.deltas.add({k.object,k.offset,oldver,oldzone,oldslot,ver,dest,slot,e.role,oldlive,1,2});++user_;app_+=e.fragment_bytes;fragment_+=e.fragment_bytes;note(m,e.update_id,e.batch_id,true);++acc_.appends;acc_.app_bytes+=e.fragment_bytes;full(dest);commit_audit(a);}
  void truncate(const LifecycleRecord&e){order(e.global_seq,-1);if(e.kind!=1||e.reserved)throw Error("reference lifecycle");Mark m=mark(e.global_seq,-1);RefAudit a{ordinal_,e.global_seq,-1,2};a.argument=e.new_size_bytes;a.update=e.update_id;a.batch=e.batch_id;auto it=by_object_.find(e.object_incarnation);if(it!=by_object_.end())for(auto id:it->second){auto&p=pages_[id];if(p.live&&p.key.offset>=e.new_size_bytes){auto&s=zones_[p.zone].log[p.slot];if(!s.valid)throw Error("reference stale truncate");a.deltas.add({p.key.object,p.key.offset,p.version,p.zone,p.slot,p.version,p.zone,p.slot,p.role,1,0,3});s.valid=false;--zones_[p.zone].live;p.live=false;}}note(m,e.update_id,e.batch_id,false);commit_audit(a);}
  void verify(bool initial)const{uint64_t occupied_blocks=0,zone_live=0,page_live=0;unsigned opens=0;for(const auto&z:zones_){if(z.log.size()>cap_||(z.state==E&&!z.log.empty())||(z.state==F&&z.log.size()!=cap_))throw Error("reference zone invariant");occupied_blocks+=z.log.size();zone_live+=z.live;opens+=z.state==O;}if(opens>1||occupied_blocks!=occupied())throw Error("reference account");for(uint32_t id=0;id<pages_.size();++id){const auto&p=pages_[id];if(!p.live)continue;++page_live;if(p.zone>=zones_.size()||p.slot>=zones_[p.zone].log.size())throw Error("reference map range");const auto&s=zones_[p.zone].log[p.slot];if(!s.valid||s.id!=id||s.version!=p.version)throw Error("reference map mismatch");}if(page_live!=zone_live||(initial&&free_count()!=h_)||(!initial&&!free_count()))throw Error("reference live/free invariant");}
  static void marker(std::ostream&o,const Mark&m){o<<"{\"event_ordinal\":"<<m.ordinal<<",\"global_seq\":"<<m.seq<<",\"page_index_within_request\":"<<m.sub<<'}';}
  static void ranges(std::ostream&o,const std::vector<uint64_t>&v){o<<'[';for(size_t i=0;i<v.size();){size_t j=i;while(j+1<v.size()&&v[j+1]==v[j]+1)++j;if(i)o<<',';o<<'['<<v[i]<<','<<v[j]<<']';i=j+1;}o<<']';}
  static void cycle_json(std::ostream&o,const RefCycle&c,size_t index){o<<"{\"cycle_index\":"<<index<<",\"start\":";marker(o,c.begin);o<<",\"last_append_before_gc\":";marker(o,c.last);o<<",\"gc_trigger\":";marker(o,c.trigger);o<<",\"allocated_new_blocks\":"<<c.appends<<",\"allocated_new_append_bytes\":"<<c.appends*4096ULL<<",\"application_returned_bytes\":"<<c.app_bytes<<",\"relocated_pages\":"<<c.moved<<",\"relocation_allocated_bytes\":"<<c.moved*4096ULL<<",\"host_wa_fraction\":\""<<c.appends+c.moved<<'/'<<c.appends<<"\",\"victim_zone\":"<<c.victim<<",\"relocation_destination\":"<<c.dest<<",\"victim_valid_fraction\":\""<<c.moved<<'/'<<c.cap<<"\",\"free_zones_before_gc\":"<<c.free_before<<",\"free_zones_after_reset\":"<<c.free_after<<",\"victim_role_pages\":{";bool first=true;for(auto[k,v]:c.roles){if(!first)o<<',';first=false;o<<'\"'<<k<<"\":"<<v;}o<<"},\"update_id_ranges\":";ranges(o,c.updates);o<<",\"batch_id_ranges\":";ranges(o,c.batches);o<<'}';}
  void comparable(std::ostream&o)const{o<<"{\"status\":\"pass\",\"sequence_only\":true,\"temporal_fields_used\":false,\"placement\":\""<<json_escape(placement_)<<"\",\"random_seed\":"<<seed_<<",\"cleaner\":\""<<cleaner_<<"\",\"initial_image\":{\"logical_bytes\":"<<initial_logical_bytes_<<",\"allocated_bytes\":"<<initial_blocks_*4096ULL<<",\"page_count\":"<<initial_blocks_<<"},\"bytes\":{\"application_returned_bytes\":"<<app_<<",\"normalized_fragment_bytes\":"<<fragment_<<",\"allocated_append_bytes\":"<<user_*4096ULL<<",\"replacement_rmw_read_bytes\":"<<rmw_<<",\"new_page_zero_fill_bytes\":"<<zero_<<",\"relocation_allocated_bytes\":"<<copied_*4096ULL<<"},\"host_wa_fraction\":\""<<user_+copied_<<'/'<<user_<<"\",\"reset_count\":"<<resets_<<",\"complete_cycle_count\":"<<cycles_.size()<<",\"tail\":{\"complete_cycle\":false,\"allocated_new_blocks\":"<<acc_.appends<<",\"allocated_append_bytes\":"<<acc_.appends*4096ULL<<",\"application_returned_bytes\":"<<acc_.app_bytes<<"},\"victim_sequence\":[";for(size_t i=0;i<victims_.size();++i){if(i)o<<',';o<<victims_[i];}o<<"],\"cycles\":[";for(size_t i=0;i<cycles_.size();++i){if(i)o<<',';cycle_json(o,cycles_[i],i+1);}o<<"],\"final_state_sha256\":\""<<digest()<<"\",\"transition_rolling_sha256\":\""<<transition_digest()<<"\"}";}
  void commit_audit(RefAudit&a){
    uint64_t live=live_total(),invalid=occupied()-live,free=free_count();
    uint8_t state=255;uint64_t wp=0,head_live=0;
    if(head_>=0){const auto&z=zones_[head_];state=z.state;wp=z.log.size();head_live=z.live;}
    const TransitionAuditRecord record{
      a.ordinal,a.seq,a.page,a.op,a.argument,a.update,a.batch,a.destination,
      a.gc,a.victim,a.moved,a.deltas.count,a.deltas.lo,a.deltas.hi,
      user_,copied_,resets_,app_,fragment_,rmw_,zero_,
      live,invalid,free,head_,state,wp,head_live};
    const auto*first=reinterpret_cast<const unsigned char*>(&record);
    audit_chunk_.insert(audit_chunk_.end(),first,first+sizeof(record));
    if(audit_chunk_.size()>=4*1024*1024){SHA256_Update(&transition_ctx_,audit_chunk_.data(),audit_chunk_.size());audit_chunk_.clear();}
  }
  std::string transition_digest()const{SHA256_CTX copy=transition_ctx_;if(!audit_chunk_.empty())SHA256_Update(&copy,audit_chunk_.data(),audit_chunk_.size());unsigned char d[32];SHA256_Final(d,&copy);std::ostringstream s;for(auto b:d)s<<std::hex<<std::setw(2)<<std::setfill('0')<<unsigned(b);return s.str();}
  std::string digest()const{SHA256_CTX ctx;SHA256_Init(&ctx);for(const auto&p:pages_){SHA256_Update(&ctx,&p.key,sizeof(p.key));SHA256_Update(&ctx,&p.version,sizeof(p.version));SHA256_Update(&ctx,&p.zone,sizeof(p.zone));SHA256_Update(&ctx,&p.slot,sizeof(p.slot));SHA256_Update(&ctx,&p.role,sizeof(p.role));uint8_t live=p.live;SHA256_Update(&ctx,&live,1);}for(uint32_t z=0;z<free_.size();++z)if(free_[z])SHA256_Update(&ctx,&z,sizeof(z));unsigned char d[32];SHA256_Final(d,&ctx);std::ostringstream s;for(auto b:d)s<<std::hex<<std::setw(2)<<std::setfill('0')<<unsigned(b);return s.str();}
};
}

int main(int argc,char**argv){try{auto begin=std::chrono::steady_clock::now();Args a(argc,argv);MappedFile im(a.need("initial")),nm(a.need("normalized")),lm(a.need("lifecycle"));auto[ih,initial]=im.records<InitialHeader,InitialRecord>("Z0BMAP1");auto[nh,normal]=nm.records<NormalHeader,NormalRecord>("Z0BNORM1");auto[lh,life]=lm.records<LifecycleHeader,LifecycleRecord>("Z0BLIFE1");if(ih->run_hash!=lh->run_hash)throw Error("run hash mismatch");Reference ref(initial,normal,life,a.u64("capacity-blocks"),a.u64("host-spares"),a.need("placement"),a.u64("random-seed",0,false),a.need("cleaner"));ref.run();std::filesystem::path outpath=a.need("output");if(std::filesystem::exists(outpath))throw Error("output exists");auto tmp=outpath;tmp+=".tmp."+std::to_string(getpid());std::ofstream out(tmp);ref.output(out);out.close();std::filesystem::rename(tmp,outpath);double seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-begin).count();rusage ru{};getrusage(RUSAGE_SELF,&ru);std::cout<<"{\"status\":\"pass\",\"events\":"<<normal.size()+life.size()<<",\"pages\":"<<ref.page_count()<<",\"wall_seconds\":"<<seconds<<",\"max_rss_kib\":"<<ru.ru_maxrss<<"}\n";return 0;}catch(const std::exception&e){std::cerr<<"z0b_native_reference: "<<e.what()<<'\n';return 1;}}
