#!/usr/bin/env python3
import argparse,hashlib,json,shutil,time
from pathlib import Path
ap=argparse.ArgumentParser();ap.add_argument('--root',type=Path,required=True);ap.add_argument('--result',type=Path,required=True);ap.add_argument('--work',type=Path,required=True);ap.add_argument('--free-before',type=int,required=True);a=ap.parse_args()
odin_path=a.result/'summary.json';odin=json.loads(odin_path.read_text());assert odin['status']=='pass';assert 'index_shadow_disk.index.tags' in odin['changed_index_files'] and 'index_shadow_disk.index.tags' in odin['recorded_index_files'];assert any(x['entry']=='sendfile' and x['triggered'] for x in odin['source_entry_audit'])
dg_path=a.root/'results/pilot3_sift10m_write_attribution_m0_r03/DGAI/m0-n100000-03/summary.json';dg=json.loads(dg_path.read_text());assert dg['status']=='pass'
b3=json.loads((a.root/'build/write-attribution-m0-v4-r02/build_manifest.json').read_text());b5=json.loads((a.root/'build/write-attribution-m0-v5-r01/build_manifest.json').read_text());assert b5['strict_superset_of_r03'] and b5['new_physical_entry']=='sendfile'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
manifest={'schema':'dynamic-vamana-write-attribution-m0-100k-closure-v1','status':'complete','scale_matrix_started':False,'anchors':[{'system':'DGAI','run':'pilot3_sift10m_write_attribution_m0_r03','attempt':'m0-n100000-03','summary':str(dg_path),'summary_sha256':sha(dg_path),'profiler_sha256':b3['profiler_sha256']},{'system':'OdinANN','run':'pilot3_sift10m_write_attribution_m0_r04','attempt':'m0-n100000-04','summary':str(odin_path),'summary_sha256':sha(odin_path),'profiler_sha256':b5['profiler_sha256']}],'profiler_relation':{'r04_strict_superset':True,'new_entry':'sendfile','dgai_r03_no_trigger_basis':'DGAI w1 uses same-prefix final_merge; conditional filesystem-copy branches are not reached and all R03 changed files were already covered'},'r04_space':{'formal_apparent_bytes':sum(p.stat().st_size for p in a.work.rglob('*') if p.is_file()),'result_apparent_bytes':sum(p.stat().st_size for p in a.result.rglob('*') if p.is_file())},'free_space_before':a.free_before,'free_space_after':shutil.disk_usage(a.result).free,'completed_unix_ns':time.time_ns()}
out=a.result.parents[1]/'closure_manifest.json';out.write_text(json.dumps(manifest,indent=2)+'\n');(a.result/'M0_V5_RUN_OK').touch();(a.result.parents[1]/'M0_100K_CLOSURE_COMPLETE').touch();print(out)
