#!/usr/bin/env bash
set -euo pipefail
[[ ${M0_WRITE_ATTRIBUTION_AUTHORIZED:-0} == 1 ]]||exit 64
((EUID==0))||{ echo 'R04 must run as root' >&2;exit 1;}
root=${ATLAS_ROOT:-/home/ubuntu/pz/VectorDB/data/VectorDB/dynamic_vamana_atlas};device=${ATLAS_NVME_MAJMIN:-259:10};chat18=$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd);chat17=/home/ubuntu/pz/VectorDB/chat/codex/share/2026-07-17/dynamic_vamana_atlas;old=/home/ubuntu/pz/VectorDB/chat/codex/share/2026-07-15/dynamic_vamana_atlas;r02=/home/ubuntu/pz/VectorDB/chat/codex/share/2026-07-16/dynamic_vamana_atlas
run=pilot3_sift10m_write_attribution_m0_r04;attempt=m0-n100000-04;work="$root/formal/$run/OdinANN/$attempt";result="$root/results/$run/OdinANN/$attempt";result_root="$root/results/$run";input="$root/results/pilot3_sift10m_write_attribution_m0_r03/inputs/n100000";build="$root/build/write-attribution-m0-v5-r01";driver="$build/install/OdinANN/w1_canary";canonical="$root/build/w1-canonical-v6/install/OdinANN/w1_canary";full="$root/datasets/sift10m/full_10m.bin";prefix="$work/index/index";trace="$input/trace.bin";expected="$input/expected_active.tags.bin";probes="$input/probes.bin";probe_spec="$input/probes.json";freeze="$root/results/pilot3_sift10m_w1_cp10_trajectory_r12/OdinANN/trajectory-cp10-12/checkpoints/cp10/cp10_freeze_evidence.json"
[[ $(findmnt -rn -T "$root" -o MAJ:MIN|awk 'NR==1{print;exit}') == "$device" ]]||exit 1
for p in "$build/M0_V5_BUILD_OK" "$build/build_manifest.json" "$driver" "$canonical" "$full" "$trace" "$expected" "$probes" "$probe_spec" "$freeze";do [[ -f $p ]]||{ echo "missing $p" >&2;exit 1;};done
[[ ! -e $work && ! -e $result_root ]]||{ echo 'refusing R04 reuse' >&2;exit 1;}
python3 -c 'import json,sys;d=json.load(open(sys.argv[1]));assert d["status"]=="pass" and d["size"]==100000 and d["master_record_range"]==[800000,900000] and d["active_count"]==8000000' "$input/manifest.json"
base=$(python3 -c 'import json,sys;from pathlib import Path;d=json.load(open(sys.argv[1]));assert d["status"]=="pass" and d["system"]=="OdinANN" and d["checkpoint"]=="cp10";print(Path(d["root_realpath"]).resolve())' "$freeze")
[[ -d $base && -f $base/IMMUTABLE_BASE_OK ]]||exit 1
available=$(df -PB1 "$root"|awk 'NR==2{print $4}');((available>=80000000000))||exit 1
if systemctl list-units --all --no-legend 'dv-m0-*'|rg -q .;then echo 'stale M0 unit' >&2;exit 1;fi
mkdir -p "$result_root";exec 9>"$root/.write_attribution_m0.lock";flock -n 9||exit 1
export W1_FORMAL_PATH_AUTHORIZED=1 W1_CLONE_PREFLIGHT_ONLY=0 W1_MUTABLE_CLONE_OWNER=ubuntu W1_ALLOWED_CLONE_TARGET="$work" W1_ALLOWED_CLONE_SYSTEM=OdinANN W1_ALLOWED_CLONE_RUN="$run" W1_ALLOWED_CLONE_ATTEMPT="$attempt" ATLAS_W1_MUTABLE_CHAT="$r02" ATLAS_ROOT="$root" ATLAS_NVME_MAJMIN="$device"
"$old/w1_clone_base.sh" OdinANN "$base" "$work";install -d -m 0700 -o ubuntu -g ubuntu "$result";install -m 0600 -o ubuntu -g ubuntu /dev/null "$result/controller.log"
profile="$result/app_write_profile_v5.json";markers="$result/markers.jsonl";resources="$result/resources.json";primer="$result/io_primer.json";online="$result/online.bin";libs="$build/lib:$root/build/gperftools-install/lib:$root/build/openblas-install/lib:$root/build/jemalloc-install/lib"
systemd-run --wait --collect --pipe --unit dv-m0-r04-odin-n100000-04 --uid ubuntu --property=Type=exec --property=AllowedCPUs=0-23 --property=CPUAccounting=yes --property=MemoryAccounting=yes --property=IOAccounting=yes --property=MemoryMax=40G --property=LimitCORE=0 --property=RuntimeMaxSec=3600 env -i PATH=/usr/bin:/bin LANG=C LC_ALL=C HOME=/home/ubuntu OPENBLAS_NUM_THREADS=8 OMP_NUM_THREADS=8 LD_LIBRARY_PATH="$libs" numactl --physcpubind=0-23 --membind=0 python3 "$chat17/w1_stage_io_primer.py" --index-root "$work/index" --device "$device" --primer-report "$primer" --resources "$resources" --resource-probe "$old/resource_probe.py" --space-root "$work/index" -- env LD_PRELOAD="$build/lib/libm0write.so" ATLAS_W1_MARKERS="$markers" ATLAS_M0_INDEX_ROOT="$work/index" ATLAS_M0_PROFILE_OUTPUT="$profile" "$driver" run "$full" "$prefix" "$trace" "$probes" "$online" >>"$result/controller.log" 2>&1
for p in "$profile" "$markers" "$resources" "$primer";do [[ -s $p ]]||exit 1;done
python3 "$old/w1_dump_active_tags.py" --tags "${prefix}_disk.index.tags" --expected "$expected" --expected-count 8000000 --output "$result/active_audit.json"
LD_LIBRARY_PATH="$libs" "$canonical" probe "$prefix" "$probes" "$result/fresh.bin" >>"$result/controller.log" 2>&1
python3 "$old/w1_visibility_probe.py" --probes "$probe_spec" --result-tags "$result/fresh.bin" --active-tags "$expected" --output "$result/fresh_probe.json"
python3 "$old/w1_visibility_probe.py" --probes "$probe_spec" --result-tags "$online" --active-tags "$expected" --output "$result/online_probe.json"
python3 "$old/w1_file_manifest.py" --root "$base" --output "$result/base_content_after.tsv";python3 "$r02/w1_mode_manifest.py" write --root "$base" --output "$result/base_mode_after.tsv";cmp -s "$work/base_content_before.tsv" "$result/base_content_after.tsv"||exit 1;cmp -s "$work/base_mode_before.tsv" "$result/base_mode_after.tsv"||exit 1
python3 "$old/w1_file_manifest.py" --root "$work/index" --output "$result/index_content_after.tsv";python3 "$r02/w1_mode_manifest.py" write --root "$work/index" --output "$result/index_mode_after.tsv"
python3 "$chat17/m0_validate_v4.py" --system OdinANN --size 100000 --input-manifest "$input/manifest.json" --build-manifest "$build/build_manifest.json" --profile "$profile" --resources "$resources" --markers "$markers" --active-audit "$result/active_audit.json" --fresh-probe "$result/fresh_probe.json" --online-probe "$result/online_probe.json" --base-before "$work/base_content_before.tsv" --base-after "$result/base_content_after.tsv" --mode-before "$work/base_mode_before.tsv" --mode-after "$result/base_mode_after.tsv" --index-before "$work/clone_content_after.tsv" --index-after "$result/index_content_after.tsv" --device "$device" --output "$result/summary.json"
python3 "$chat18/m0_finalize_r04_closure.py" --root "$root" --result "$result" --work "$work" --free-before "$available"
chmod -R a-w "$result";echo "$result_root/closure_manifest.json"
